baseURL = 'http://localhost:1313/'
languageCode = 'es'
title = 'Armado de PC'
theme = 'book'
enableGitInfo = true
defaultContentLanguage = 'es'
[pagination]
pagerSize = 10

[params]
  BookTheme = 'auto' # claro/oscuro/auto
  BookToC = true     # Muestra tabla de contenidos a la izquierda
  BookSection = '*'
  BookSearch = true  # Habilita buscador interno
  BookLogo = 'img/logo.png' # si querés poner un logo personalizado

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # permite HTML dentro de Markdown

[outputs]
  home = ["HTML", "RSS", "JSON"]
